"""Generate Dart: FFI bindings + Flutter main.dart + pubspec.yaml.

Inputs:
  - ffi_units: FuncUnits that are C-ABI exported (scalar signatures)
  - tree: widget tree from ui.parse_ui
  - state_fields: set of state field names
"""
from __future__ import annotations

from .analyzer import FuncUnit
from .ffi import DART_FFI_TYPE, DART_NATIVE_TYPE, dart_name
from .ui import collect_state
from .styling import (style_to_flutter_text, style_to_flutter_padding,
                      style_to_flutter_box, style_to_flutter_main_align,
                      parse_style)

_STYLE = {
    "headline": "TextStyle(fontSize: 28, fontWeight: FontWeight.bold)",
    "title": "TextStyle(fontSize: 20, fontWeight: FontWeight.bold)",
    "subtitle": "TextStyle(fontSize: 16, color: Colors.grey[700])",
    "body": "TextStyle(fontSize: 16)",
}
_ALIGN = {"center": "center", "start": "start", "end": "end",
          "spaceBetween": "spaceBetween", "spaceEvenly": "spaceEvenly",
          "spaceAround": "spaceAround"}


def _ret_type(units: list[FuncUnit], name: str) -> str:
    for u in units:
        if u.name == name:
            return u.ret_type
    return "float"


def generate_bindings(ffi_units: list[FuncUnit], lib_basename: str,
                      func_backends: dict[str, str] | None = None,
                      lib_names: dict[str, str] | None = None) -> str:
    """Generate Dart FFI bindings.

    func_backends: maps function name -> backend ('rust' or 'cpp').
        If None or empty, all functions use the single lib_basename.
    lib_names: maps backend -> shared lib basename for that group.
        If None or empty, all functions load from lib_basename.
    """
    lines = [
        "// AUTO-GENERATED by pyeffic. Do not edit by hand.",
        "import 'dart:ffi';",
        "import 'dart:io';",
        "",
    ]
    # typedefs + lookups
    for u in ffi_units:
        dn = dart_name(u.name)
        native_params = ", ".join(DART_FFI_TYPE[t] for _, t in u.params)
        dart_params = ", ".join(DART_NATIVE_TYPE[t] for _, t in u.params)
        ret_n = DART_FFI_TYPE[u.ret_type]
        ret_d = DART_NATIVE_TYPE[u.ret_type]
        lines.append(f"typedef {dn}Native = {ret_n} Function({native_params});")
        lines.append(f"typedef {dn}Dart = {ret_d} Function({dart_params});")
    lines.append("")
    lines.append("class NativeLib {")

    # determine if we need multiple DLLs
    backends_used = set()
    if func_backends:
        for u in ffi_units:
            b = func_backends.get(u.name)
            if b:
                backends_used.add(b)
    multi = len(backends_used) > 1

    if multi:
        # multi-backend: one DynamicLibrary per backend
        for b in sorted(backends_used):
            lines.append(f"  late final DynamicLibrary _lib_{b};")
    else:
        lines.append("  late final DynamicLibrary _lib;")

    for u in ffi_units:
        lines.append(f"  late final {dart_name(u.name)}Dart {dart_name(u.name)};")
    lines.append("")
    lines.append("  NativeLib() {")

    if multi:
        for b in sorted(backends_used):
            lname = lib_names.get(b, lib_basename) if lib_names else lib_basename
            lines.append(f"    final name_{b} = Platform.isWindows")
            lines.append(f"        ? '{lname}.dll'")
            lines.append(f"        : Platform.isLinux")
            lines.append(f"        ? 'lib{lname}.so'")
            lines.append(f"        : 'lib{lname}.dylib';")
            lines.append(f"    _lib_{b} = DynamicLibrary.open(name_{b});")
    else:
        lines.append("    final name = Platform.isWindows")
        lines.append(f"        ? '{lib_basename}.dll'")
        lines.append("        : Platform.isLinux")
        lines.append(f"        ? 'lib{lib_basename}.so'")
        lines.append(f"        : 'lib{lib_basename}.dylib';")
        lines.append("    _lib = DynamicLibrary.open(name);")

    for u in ffi_units:
        dn = dart_name(u.name)
        b = func_backends.get(u.name) if func_backends else None
        if multi and b:
            lines.append(f"    {dn} = _lib_{b}.lookupFunction<{dn}Native, {dn}Dart>('{u.name}');")
        else:
            lines.append(f"    {dn} = _lib.lookupFunction<{dn}Native, {dn}Dart>('{u.name}');")
    lines.append("  }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _widget_dart(node, state_fields: set[str], indent: int, _id_counter: list | None = None) -> str:
    pad = "  " * indent
    if _id_counter is None:
        _id_counter = [0]
    if not isinstance(node, dict):
        _id_counter[0] += 1
        ref = f"ge:Text:{_id_counter[0]}"
        return f"{pad}GeTagged(ref: {ref!r}, child: Text({node!r}))"
    k = node.get("kind")
    _id_counter[0] += 1
    ref = f"ge:{k}:{_id_counter[0]}"
    if k == "Text":
        sd = node.get("style_dict", {})
        if node.get("state"):
            ts = style_to_flutter_text(sd) if sd else _STYLE.get("title", _STYLE["body"])
            inner = f"Text(_{node['state']}, style: {ts})"
        else:
            ts = style_to_flutter_text(sd) if sd else _STYLE.get(node.get("style", "body"), _STYLE["body"])
            inner = f"Text({_dart_str(node['text'])}, style: {ts})"
        return f"{pad}GeTagged(ref: {ref!r}, child: {inner})"
    if k in ("Column", "Row"):
        children = node.get("children", [])
        sd = node.get("style_dict", {})
        main_axis = sd.get("align", node.get("align", "center")) if sd else node.get("align", "center")
        main_expr = style_to_flutter_main_align({"align": main_axis})
        cross = "start" if k == "Row" else "center"
        inner = ",\n".join(_widget_dart(c, state_fields, indent + 3, _id_counter) for c in children)
        return (f"{pad}GeTagged(ref: {ref!r}, child: {k}(\n"
                f"{pad}    mainAxisAlignment: {main_expr},\n"
                f"{pad}    crossAxisAlignment: CrossAxisAlignment.{cross},\n"
                f"{pad}    children: [\n{inner}\n{pad}    ],\n{pad}))")
    if k == "Container":
        child = node.get("child")
        sd = node.get("style_dict", {})
        color = node.get("color", "")
        if "padding" in sd:
            pad_expr = style_to_flutter_padding(sd)
        else:
            pad_expr = f"EdgeInsets.all({node.get('padding', 8)})"
        box = style_to_flutter_box(sd)
        if not box and color:
            box = f"BoxDecoration(color: Colors.{color})"
        box_part = f"decoration: {box},\n{pad}    " if box else ""
        child_s = _widget_dart(child, state_fields, indent + 3, _id_counter) if child else f"{'  '*(indent+3)}const SizedBox.shrink()"
        return (f"{pad}GeTagged(ref: {ref!r}, child: Container(\n"
                f"{pad}    padding: const {pad_expr},\n"
                f"{pad}    {box_part}child: {child_s.strip()},\n{pad}))")
    if k == "Button":
        label = node.get("label", "")
        action = node.get("action")
        handler = "null"
        if isinstance(action, list) and action and action[0].get("call"):
            handler = action[0].get("_handler", f"_{action[0]['call']}")
        return (f"{pad}GeTagged(ref: {ref!r}, child: ElevatedButton(\n"
                f"{pad}    onPressed: {handler},\n"
                f"{pad}    child: Text({_dart_str(label)}),\n{pad}))")
    if k == "SizedBox":
        h = node.get("height", 0)
        w = node.get("width", 0)
        if h and w:
            return f"{pad}GeTagged(ref: {ref!r}, child: SizedBox(height: {h}, width: {w}))"
        if h:
            return f"{pad}GeTagged(ref: {ref!r}, child: SizedBox(height: {h}))"
        if w:
            return f"{pad}GeTagged(ref: {ref!r}, child: SizedBox(width: {w}))"
        return f"{pad}GeTagged(ref: {ref!r}, child: const SizedBox.shrink())"
    if k == "Divider":
        return f"{pad}GeTagged(ref: {ref!r}, child: const Divider(thickness: 1))"
    if k == "Expanded":
        child = node.get("child")
        child_s = _widget_dart(child, state_fields, indent + 1, _id_counter) if child else f"{pad}const SizedBox.shrink()"
        flex = node.get("flex", 1)
        return f"{pad}GeTagged(ref: {ref!r}, child: Expanded(flex: {flex}, child: {child_s.strip()}))"
    return f"{pad}GeTagged(ref: {ref!r}, child: Text('unsupported: {k}'))"


def _handler_method(action_name: str, ffi_units: list[FuncUnit]) -> str:
    """Generate a Dart handler method for an Action."""
    # find the unit with this name
    unit = next((u for u in ffi_units if u.name == action_name), None)
    if unit is None:
        return f"  void _{action_name}() {{ /* FFI fn '{action_name}' not exported */ }}\n"
    dn = dart_name(unit.name)
    args = ", ".join(str(a) for a in [])  # filled below
    # We need the action's args; this method is built per-button in generate_main
    return ""  # placeholder; real handlers built in generate_main


def generate_main(tree: dict, ffi_units: list[FuncUnit], app_title: str,
                   dart_source: str = "") -> str:
    state_fields = collect_state(tree)
    # discover buttons (each has a list of actions for multi-update)
    buttons = []

    def walk(n):
        if isinstance(n, dict):
            if n.get("kind") == "Button" and isinstance(n.get("action"), list):
                buttons.append(n)
            for key in ("children", "child"):
                v = n.get(key)
                if isinstance(v, list):
                    for c in v:
                        walk(c)
                elif isinstance(v, dict):
                    walk(v)

    walk(tree)

    # assign unique handler names per button (based on first action's call)
    seen: dict[str, int] = {}
    for btn in buttons:
        acts = btn["action"]
        if not acts:
            continue
        base = acts[0].get("call", "handler")
        if base not in seen:
            seen[base] = 1
            hname = f"_{base}"
        else:
            seen[base] += 1
            hname = f"_{base}_{seen[base]}"
        # store handler name on the first action (read by _widget_dart)
        acts[0]["_handler"] = hname
        btn["_handler_name"] = hname

    body_widget = _widget_dart(tree, state_fields, 6, [0])

    # state fields
    state_decls = "\n".join(f"  String _{f} = '';" for f in sorted(state_fields)) or "  // no state"

    # handlers — one per button, calling all its actions in a single setState
    handlers = []
    for btn in buttons:
        acts = btn.get("action", [])
        if not acts:
            continue
        hname = btn.get("_handler_name", f"_{acts[0].get('call', 'handler')}")
        body_lines = []
        setstate_lines = []
        for act in acts:
            call = act.get("call", "")
            unit = next((u for u in ffi_units if u.name == call), None)
            dn = dart_name(call)
            args = ", ".join(_dart_arg(a) for a in act.get("args", []))
            update = act.get("update", "")
            if unit is None:
                body_lines.append(f"    // FFI fn '{call}' not exported")
                continue
            ret = unit.ret_type
            if ret == "float":
                body_lines.append(f"    final r_{update} = _lib.{dn}({args});")
                setstate_lines.append(f"      _{update} = r_{update}.toStringAsFixed(2);")
            elif ret == "int":
                body_lines.append(f"    final r_{update} = _lib.{dn}({args});")
                setstate_lines.append(f"      _{update} = r_{update}.toString();")
            elif ret == "bool":
                body_lines.append(f"    final r_{update} = _lib.{dn}({args});")
                setstate_lines.append(f"      _{update} = r_{update} ? 'true' : 'false';")
            else:
                body_lines.append(f"    _lib.{dn}({args});")
        if setstate_lines:
            body_lines.append(f"    setState(() {{\n"
                              + "\n".join(setstate_lines) + "\n    });")
        else:
            body_lines.append("    setState(() {});")
        handlers.append(f"  void {hname}() {{\n" + "\n".join(body_lines) + "\n  }")
    handlers_s = "\n\n".join(handlers) or "  // no handlers"

    return f"""// AUTO-GENERATED by pyeffic. Do not edit by hand.
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'bindings.dart';
{dart_source}

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {{
  const MyApp({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return MaterialApp(
      title: {app_title!r},
      home: const HomePage(),
    );
  }}
}}

class HomePage extends StatefulWidget {{
  const HomePage({{super.key}});

  @override
  State<HomePage> createState() => _HomePageState();
}}

class _HomePageState extends State<HomePage> {{
  final NativeLib _lib = NativeLib();

{state_decls}

{handlers_s}

  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      appBar: AppBar(title: Text({app_title!r})),
      body: SafeArea(
        child: GeInspector(
          child: SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: {body_widget.strip()},
            ),
          ),
        ),
      ),
      floatingActionButton: const GeInspectorToggle(),
    );
  }}
}}

/// Tags a widget with a source reference for the GE inspector.
/// When inspector mode is enabled, tapping this widget copies its ref to clipboard.
class GeTagged extends StatelessWidget {{
  final String ref;
  final Widget child;
  const GeTagged({{super.key, required this.ref, required this.child}});

  @override
  Widget build(BuildContext context) {{
    if (GeInspectorState.isEnabled) {{
      return GestureDetector(
        onTap: () {{
          Clipboard.setData(ClipboardData(text: ref));
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Copied: $ref'),
              duration: const Duration(seconds: 2),
            ),
          );
        }},
        child: Container(
          decoration: BoxDecoration(
            border: Border.all(color: Colors.blue.withOpacity(0.3), width: 1),
          ),
          child: child,
        ),
      );
    }}
    return child;
  }}
}}

/// Toggle button for inspector mode.
class GeInspectorToggle extends StatefulWidget {{
  const GeInspectorToggle({{super.key}});
  @override
  State<GeInspectorToggle> createState() => _GeInspectorToggleState();
}}

class _GeInspectorToggleState extends State<GeInspectorToggle> {{
  @override
  Widget build(BuildContext context) {{
    return FloatingActionButton(
      mini: true,
      backgroundColor: GeInspectorState.isEnabled ? Colors.blue : Colors.grey,
      onPressed: () {{
        setState(() {{
          GeInspectorState.isEnabled = !GeInspectorState.isEnabled;
        }});
      }},
      child: Icon(GeInspectorState.isEnabled ? Icons.bug_report : Icons.bug_report_outlined),
    );
  }}
}}

/// Global state for the GE inspector.
class GeInspectorState {{
  static bool isEnabled = false;
}}

/// Wraps the app body with inspector overlay support.
class GeInspector extends StatelessWidget {{
  final Widget child;
  const GeInspector({{super.key, required this.child}});

  @override
  Widget build(BuildContext context) {{
    return child;
  }}
}}
"""


def _dart_str(s) -> str:
    """Produce a Dart string literal with $ escaped (no interpolation)."""
    return repr(str(s)).replace("$", "\\$")


def _dart_arg(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, int):
        return str(v)
    return repr(str(v))


def generate_pubspec(app_name: str) -> str:
    return f"""name: {app_name}
description: Generated by pyeffic (Python -> Flutter + native FFI).
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
"""
